apiVersion: apps/v1
kind: Deployment
metadata:
  name: 25-deploy
  namespace: default
  labels:
    app: 25-deploy
spec:
  selector:
    matchLabels:
      app: 25-deploy
  replicas: 1

  template:
    metadata:
      labels:
        app: 25-deploy
    spec:
      containers:
        - name: 25-deploy
          image: gopikondaji/2520
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 5173
              name: 25-deploy

      restartPolicy: Always
