apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: default
  labels:
    app: frontend-deploy
spec:
  selector:
    matchLabels:
      app: frontend-deploy
  replicas: 1

  template:
    metadata:
      labels:
        app: frontend-deploy
    spec:
      containers:
        - name: frontend-deploy
          image: gopikondaji/frontend
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 5173
              name: frontend-deploy

      restartPolicy: Always
