apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  mongo-user: dGVzdAo=
  mongo-password: dGVzdAo=
  # Example:
  # password: {{ .Values.password | b64enc }}